version: '3'
services:
  mongo:
    image: mongo:3.4.2
    ports:
      - '27017:27017'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./server/data:/data/db:rw
    restart: always
    command: --smallfiles
